# Generated by Django 5.2.16 on 2026-08-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_max_participants_alter_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_participant_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
