# Generated by Django 5.2.16 on 2026-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_last_participant_left_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_all_speak',
            field=models.BooleanField(default=True),
        ),
    ]
