# Generated by Django 5.2.16 on 2026-08-05 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_allow_all_speak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_participant_left_at',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=50)),
                ('is_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.room')),
            ],
            options={
                'unique_together': {('room', 'identity')},
            },
        ),
    ]
